version: '3.8'
services:
  frontend1:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app/src  # Optional: for development
    restart: unless-stopped

  frontend2:
    build: 
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app/src  # Optional: for development
    restart: unless-stopped

  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx/loadbalancer.conf:/etc/nginx/nginx.conf
      - ./src:/app/src  # Optional: for development
    ports:
      - "80:80"
    depends_on:
      - frontend1
      - frontend2
    restart: unless-stopped